skill_aliases = {
    "atlassian jira": ["jira"],
    "oracle java": ["java"],
    "microsoft windows": ["windows"],
    "microsoft sql server": ["sql server", "ms sql server"],
    "microsoft sharepoint": ["sharepoint"],
    "microsoft active directory": ["active directory"],
    "oracle solaris": ["solaris"],
    "red hat enterprise linux": ["redhat linux", "red hat linux", "rhel"],
    "hp-ux": ["hpux", "hp ux"],
    "ibm aix": ["aix"],
    "amazon elastic compute cloud": ["amazon ec2", "ec2"],
    "amazon simple storage service": ["amazon s3", "s3"],
    "amazon simple queue service": ["amazon sqs", "sqs"],
    "apache http server": ["apache"],
    "apache tomcat": ["tomcat"],
    "oracle weblogic server": ["weblogic"],
    "ibm websphere": ["websphere"],
    "ibm websphere mq": ["websphere mq", "mq"],
    "internet information services": ["microsoft iis", "iis"],
    "veritas netbackup": ["netbackup", "net backup"],
    "veritas volume manager": ["volume manager", "vxvm"],
    "ibm tivoli": ["tivoli"],
    "ibm tivoli storage manager": ["tivoli storage manager", "tsm"],
    "teradata database": ["teradata"],
    "oracle database": ["oracle"],
    "ibm db2": ["db2"],
    "sybase": ["sybase"],
    "single sign on": ["sso"],
    "internet protocol security": ["ipsec"],
    "secure shell": ["ssh"],
    "secure sockets layer": ["ssl"],
    "secure file transfer protocol": ["sftp"],
    "vmware esx": ["esx"],
    "vmware": ["vsphere", "virtual machine", "virtualization"],
    "openstack": ["open stack"],
    "nmap": ["nmap"],
    "snort": ["snort"],
    "samba": ["samba"],
    "nagios": ["nagios"],
    "netcool": ["netcool"],
    "perl": ["perl"],
    "bash": ["bash"],
    "awk": ["awk"],
    "bourne shell": ["bourne shell"],
    "korn shell": ["korn", "ksh"],
    "xml": ["xml"],
    "netstat": ["netstat"],
    "microsoft .net": ["net", ".net"]
}

transfer_skill_keywords = {
    "customer service": ["customer", "customers", "complaints", "greet", "assist customers", "customer needs"],
    "communication": ["speaking", "answer questions", "telephones", "give information", "explain", "greeting"],
    "sales": ["sales", "sell", "recommend products", "promote sales", "merchandise"],
    "active listening": ["active listening", "customer wants", "customer needs", "listening"],
    "critical thinking": ["critical thinking", "resolve", "correct problems", "handle situations", "prevent"],
    "reading comprehension": ["reading comprehension", "policies", "procedures"],
    "judgment and decision making": ["judgment and decision making", "judgement and decision making", "decision making"],
    "social perceptiveness": ["social perceptiveness", "difficult situations", "customer needs"],
    "persuasion": ["persuasion", "recommend", "promote"],
    "clerical": ["clerical", "records", "receipts", "reports", "vouchers"],
    "coordination": ["coordination", "coordinate", "arrange", "set up"],
    "monitoring": ["monitoring", "monitor", "watch", "check"],
    "time management": ["time management", "shift", "daily"],
    "negotiation": ["negotiation"],
    "mathematics": ["mathematics", "calculate", "count money", "cash drawers"],
    "service orientation": ["service oriented", "serve", "assist", "help"],
    "food production": ["food production", "food preparation", "prepare food", "beverages", "meals"],
    "active learning": ["active learning", "learn"],
    "learning strategies": ["learning strategies"],
    "instructing": ["instructing", "train", "training"],
    "production and processing": ["production and processing", "processing", "stock", "inventory"],
    "education and training": ["education and training", "training"]
}